name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 92.4.68.199
        username: opc
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/mysite
          git pull
          sudo docker stop $(sudo docker ps -q)
          sudo docker build -t mohit-site .
          sudo docker run -d -p 8085:80 mohit-site
